package client.model.gamemap.mapelements;

import messagesbase.messagesfromclient.EMove;

/**
 * 
 */
public class Coordinates {

	/**
	 * Attributes:
	 */

	private final int X;
	private final int Y;
	
	
	public int getX() {
		return X;
	}

	public int getY() {
		return Y;
	}

	
	/**
	 * Methods:
	 */
	/**
	 * Default Ctor
	 */
	public Coordinates () {
		this(-1, -1);
	}
	
	/**
	 * @param X
	 * @param Y
	 */
	public Coordinates(int X, int Y) {
		this.X = X;
		this.Y = Y;
	}

	public Coordinates getCoordinatesToThe(EMove moveDir) {
		switch (moveDir) {
		case EMove.Left:
			return  new Coordinates(X - 1, Y);
		case EMove.Right:
			return new Coordinates(X + 1, Y);
		case EMove.Up:
			return  new Coordinates(X, Y + 1);
		case EMove.Down:
			return  new Coordinates(X, Y - 1);
		default:
			throw new IllegalArgumentException("Invalid direction");
		}
	}
	
	// auto generated by ChatGPT 3.5
	@Override
	public boolean equals(Object obj) {
	    if (this == obj) {
	        return true; // Reference equality
	    }
	    if (obj == null || getClass() != obj.getClass()) {
	        return false; // Null or different class
	    }
	    Coordinates other = (Coordinates) obj;
	    return this.X == other.X && this.Y == other.Y; // Compare fields
	}

	// auto generated by ChatGPT 3.5
	@Override
	public int hashCode() {
	    // Combine fields into a single hash value
	    return 31 * Integer.hashCode(X) + Integer.hashCode(Y);
	}


	
	public String toString() {
		return "[" + X + ", " + Y + "]";
	}
}



